<a href="https://colab.research.google.com/github/sosullivan7221/sqlite_database_operations/blob/main/WK3_504.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Week 3 = SQL in Python

## Packages

In [48]:
import pandas as pd
from sqlalchemy import create_engine
import sqlite3

## Dataset Analysis

### First Set

In [17]:
df1 = pd.read_csv('https://raw.githubusercontent.com/hantswilliams/HHA_504_2023/main/WK3/data/stonybrook/stonybrook.csv')

df1.shape

(7710, 57)

In [18]:
df1.sample(10)

# There are a number of columns for many different insurance types, which is likely the reason for so many null values within them. Each encounter won't be using each of the insurance plans listed in the table, creating the null value.

,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
2880,58925,REMOVAL OF CYSTS OF OVARIES,Outpatient,Package,17836.89,17836.89,6580.50,6580.50,6580.50,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
158,11976,REMOVAL OF IMPLANTABLE CONTRACEPTIVE CAPSULES,Outpatient,Line,2098.86,2098.86,113.42,2050.50,955.38,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,702.22,NaN,NaN
6396,336,PERITONEAL ADHESIOLYSIS WITH COMPLICATION,Inpatient,Line,63720.13,63720.13,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3692,73565,X-RAY OF BOTH KNEES WHILE STANDING,Outpatient,Line,426.00,426.00,92.92,92.92,92.92,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4689,87209,SPECIAL STAIN FOR PARASITES,Outpatient,Line,79.38,79.38,5.85,53.04,24.99,NaN,...,NaN,53.04,NaN,NaN,NaN,NaN,NaN,5.85,25.11,NaN
7042,43940824,RESEARCH TIME PETMR ADD 3HR,NaN,NaN,5485.00,5485.00,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6099,058X,Other Disorders Of Nervous System,Inpatient,Line,55093.00,55093.00,5104.58,42907.00,17154.80,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8554.70,NaN,NaN
3492,70496,CT SCAN OF BLOOD VESSELS OF HEAD WITH CONTRAST,Outpatient,Line,4933.46,4933.46,249.06,4881.00,1229.42,NaN,...,500.04,NaN,NaN,500.04,3015.55,514.89,NaN,301.57,NaN,NaN
781,25651,PLACEMENT OF STABILIZING DEVICE FOR BROKEN BAS...,Outpatient,Line,3500.98,3500.98,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5204,95885,NEEDLE MEASUREMENT OF ELECTRICAL ACTIVITY IN A...,Outpatient,Line,916.00,916.00,210.19,210.19,210.19,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df1.describe()

,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,1199-Commercial other,Aetna-Medicare Advantage HMO,Aetna-Commercial HMO/POS,Aetna-Commercial PPO/Open Access,Aetna-Commercial other,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
count,7.710000e+03,7.710000e+03,6254.000000,6.254000e+03,6254.000000,1014.000000,1106.000000,1827.000000,1612.000000,128.000000,...,943.000000,1777.000000,0.0,434.000000,2357.000000,624.000000,133.000000,2065.000000,357.000000,46.000000
mean,2.274832e+04,2.274832e+04,4090.693876,1.003579e+04,6315.587725,5791.542456,5614.005027,4320.418248,4436.188381,1703.756250,...,10868.205705,2572.653849,NaN,2070.212120,5977.464298,4438.776234,3261.594586,2454.314228,789.416667,702.261087
std,7.470570e+04,7.470570e+04,10576.213503,2.915075e+04,14601.846406,24302.352403,12671.487487,8718.537182,8881.733882,5124.232802,...,20703.429246,4036.667401,NaN,8501.228677,16227.981498,9982.579323,10266.478193,11009.140577,2880.486830,1717.006016
min,3.000000e-02,3.000000e-02,0.010000,1.000000e-01,0.030000,0.010000,1.100000,0.020000,0.500000,0.590000,...,2.370000,0.010000,NaN,1.000000,0.010000,1.330000,0.190000,0.010000,0.180000,2.480000
25%,1.065895e+03,1.065895e+03,96.520000,6.982500e+02,403.117500,148.797500,125.070000,277.900000,312.750000,110.387500,...,200.450000,197.880000,NaN,71.220000,258.500000,96.290000,129.000000,42.980000,8.400000,26.810000
50%,4.745295e+03,4.745295e+03,1108.860000,4.311000e+03,2600.740000,974.400000,714.860000,2153.000000,2153.000000,404.500000,...,1700.200000,1932.380000,NaN,236.230000,1571.000000,387.500000,444.000000,425.790000,34.830000,82.710000
75%,1.103881e+04,1.103881e+04,4309.532500,8.170000e+03,5870.540000,4592.000000,5782.430000,4822.000000,4822.000000,1778.920000,...,13359.895000,4704.000000,NaN,1486.947500,5127.000000,3531.920000,2257.430000,1753.100000,286.800000,235.000000
max,1.857952e+06,1.857952e+06,327869.690000,1.302636e+06,370099.900000,331304.280000,157848.600000,99999.990000,96372.570000,54838.130000,...,277267.380000,80891.260000,NaN,154940.610000,291490.750000,92493.910000,88051.340000,327869.690000,26350.000000,7195.400000

In [13]:
df1['Type'].value_counts()

Outpatient    6041
Inpatient      886
Name: Type, dtype: int64

In [15]:
df1['Description'].value_counts()

R&B MED 05CA SEMI-PRIVATE/2                                                                   3
R&B SHA 05PS/11PS SEMI-PRIVATE                                                                3
DESTRUCTION OF FIRST DIVISION OF FACE NERVE BRANCH                                            2
INJECTION OF CHEMICAL FOR PARALYSIS OF SALIVARY GLANDS ON BOTH SIDES OF MOUTH                 2
INJECTION OF CHEMICAL FOR PARALYSIS OF FACIAL AND NECK NERVE MUSCLES ON BOTH SIDES OF FACE    2
                                                                                             ..
ANCHOR/SCREW FOR OPPOSING BONE-TO-BONE OR SOFT TISSUE-TO-BONE (IMPLANTABLE)                   1
BRACHYTHERAPY NEEDLE                                                                          1
CARDIOVERTER-DEFIBRILLATOR, DUAL CHAMBER (IMPLANTABLE)                                        1
CARDIOVERTER-DEFIBRILLATOR, SINGLE CHAMBER (IMPLANTABLE)                                      1
SEMI-PRIVATE                                                                                  1
Name: Description, Length: 5449, dtype: int64

### Second Set

In [21]:
df2 = pd.read_json('/content/data/133957095_NewYorkPresbyterianHospital_standardcharges.json')

df2.shape

(6193, 47)

In [24]:
df2.sample(10)

# This set doesn't seem to have null values for different insurances, but does specify if a charge is nto seperately payable from any of the gross charges for each insurance

,Code (CPT/DRG),Description,Rev Code,Inpatient/Outpatient,Gross Charges,Discounted Cash Price,Aetna,Cigna,Empire Blue Cross Blue Shield,Emblem Health,...,Consumer Health Network,Devon,Equian,First Health,Magnacare,Multiplan/Beechstreet/PHCS,QHM,Worldwide,Minimum Negotiated Charge,Maximum Negotiated Charge
4225,D2662,HC DENTAL ONLAY RESIN COMPOSITE 2 SURFACES,0512,Inpatient/Outpatient,2553.000000,2553.000000,Not separately payable,Not separately payable,1787.1,Not separately payable,...,1160.0832,1160.0832,1160.0832,1160.0832,1160.0832,1160.0832,1160.0832,1160.0832,255.001112,2042.400000
4485,D6065,HC IMPLANT SUPPORTED PORCELAIN/CERAMIC CRWN,0512,Inpatient/Outpatient,3671.000000,3671.000000,Not separately payable,Not separately payable,2569.7,Not separately payable,...,1668.1024,1668.1024,1668.1024,1668.1024,1668.1024,1668.1024,1668.1024,1668.1024,1668.102400,2936.800000
5793,424,OTHER HEPATOBILIARY OR PANCREAS O.R. PROCEDURE...,Multiple,Inpatient,86744.026167,86744.026167,81896.7136,93406.522638,237112.776479,108722.05604,...,39416.48549,39416.48549,39416.48549,39416.48549,39416.48549,39416.48549,39416.48549,39416.48549,19538.066739,237112.776479
3516,97537,HC OT COMMUNITY/WORK REINTEGRATION 15 MIN,0430,Inpatient/Outpatient,270.000000,270.000000,200.07,232,330.8283,221.53,...,122.688,122.688,122.688,122.688,122.688,122.688,122.688,122.688,35.450000,361.504640
6111,854,INFECTIOUS AND PARASITIC DISEASES WITH O.R. PR...,Multiple,Inpatient,144492.358980,144492.358980,71074.4256,81063.264348,94978.1798,94354.91784,...,65657.32792,65657.32792,65657.32792,65657.32792,65657.32792,65657.32792,65657.32792,65657.32792,10543.626000,94978.179800
1099,75825,HC X-RAY VENOGRAPHY INFERIOR VENA CAVA,0320,Inpatient/Outpatient,8804.000000,8804.000000,6523.764,3732.896,742.126,8713.138594,...,4000.5376,4000.5376,4000.5376,4000.5376,4000.5376,4000.5376,4000.5376,4000.5376,431.146802,8713.138594
5149,95887,HC EMG NON-EXTREMITY W/NERVE CONDUCTION,0922,Inpatient/Outpatient,368.000000,368.000000,272.688,210.128,493.4182,295.872,...,167.2192,167.2192,167.2192,167.2192,167.2192,167.2192,167.2192,167.2192,167.219200,527.826743
4886,70544,HC MR ANGIOGRAPHY HEAD W/O CONTRAST,0615,Inpatient/Outpatient,4062.000000,4062.000000,3009.942,1722.288,1947.8635,1236.003504,...,1845.7728,1845.7728,1845.7728,1845.7728,1845.7728,1845.7728,1845.7728,1845.7728,286.062000,3009.942000
4819,D9975,HC DENTAL EXTERNAL BLEACHING FOR HOME APPLICAT...,0512,Inpatient/Outpatient,92.000000,92.000000,Not separately payable,Not separately payable,64.4,Not separately payable,...,41.8048,41.8048,41.8048,41.8048,41.8048,41.8048,41.8048,41.8048,41.804800,396.311105
3151,66600,REMOVE IRIS AND LESION,0360,Inpatient/Outpatient,17577.000000,17577.000000,9144,7496,13737,9474.4,...,7986.9888,7986.9888,7986.9888,7986.9888,7986.9888,7986.9888,7986.9888,7986.9888,2412.000000,13737.000000

In [27]:
df2.describe()

,Gross Charges,Discounted Cash Price,Minimum Negotiated Charge,Maximum Negotiated Charge
count,6.193000e+03,6.193000e+03,5912.000000,5.912000e+03
mean,3.385988e+04,3.385988e+04,2249.918880,2.390277e+04
std,1.062409e+05,1.062409e+05,6015.717204,7.136503e+04
min,1.000000e+00,1.000000e+00,0.454400,1.608000e+00
25%,5.970000e+02,5.970000e+02,122.228437,6.380010e+02
50%,3.925000e+03,3.925000e+03,431.142905,4.086731e+03
75%,3.033600e+04,3.033600e+04,2107.000000,1.925640e+04
max,2.538980e+06,2.538980e+06,204861.126000,1.713460e+06

In [25]:
df2['Description'].value_counts()

KNEE ARTHROSCOPY/SURGERY                                                         16
REPAIR EYELID DEFECT                                                             12
CYSTOSCOPY AND TREATMENT                                                         12
TREAT HUMERUS FRACTURE                                                            9
SHOULDER ARTHROSCOPY/SURGERY                                                      7
                                                                                 ..
AMPUTATION TOE METATARSAL                                                         1
AMPUTATION THRU METATARSAL                                                        1
AMPUTATION OF MIDFOOT                                                             1
REVISION OF FOOT BONES                                                            1
NON-EXTENSIVE O.R. PROCEDURES UNRELATED TO PRINCIPAL DIAGNOSIS WITHOUT CC/MCC     1
Name: Description, Length: 5925, dtype: int64

In [26]:
df2['Inpatient/Outpatient'].value_counts()

Inpatient/Outpatient    5470
Inpatient                723
Name: Inpatient/Outpatient, dtype: int64

## SQL Table Creation

### Creating from Scratch

In [46]:
# Initiate Connection

conn = sqlite3.connect('health.db')
c = conn.cursor()

In [50]:
# Create Table

c.execute('''
    CREATE TABLE price_chart
      (
        [Code] real,
        [Type] text,
        [Package/Line_Level] text,
        [Gross_charge] real,
        [Discounted_cash_price] real

      );

''')

conn.commit()

In [53]:
# Insert Into Manual

sql_query1 = """
    INSERT INTO price_chart (
      'Code',
      'Type',
      'Package/Line_Level',
      'Gross_charge',
      'Discounted_cash_price'
    )
    values (
      42416,
      'Inpatient',
      'Package',
      500.00,
      400.00
    );
"""

c.execute(sql_query1)

In [54]:
# Second Insert

sql_query2 = """
    INSERT INTO price_chart (
      'Code',
      'Type',
      'Package/Line_Level',
      'Gross_charge',
      'Discounted_cash_price'
    )
    values (
      85781,
      'Outpatient',
      'Line',
      1000.00,
      750.00
    );
"""

c.execute(sql_query2)

In [56]:
# Test to see if inserted

sql_query3 = '''
SELECT *
FROM price_chart;
'''

c.execute(sql_query3)
print(c.fetchall())

[(42416.0, 'Inpatient', 'Package', 500.0, 400.0), (85781.0, 'Outpatient', 'Line', 1000.0, 750.0)]

### Automatic Insertion from Dataset

In [59]:
# Inserting smaller portion of dataset

df1_small = df1.head(1000)

df1_small.to_sql('price_chart', conn, if_exists='replace')

1000

In [60]:
# Test

test_query = '''
SELECT *
FROM price_chart
limit 10;
'''

response = pd.read_sql(test_query, conn)
response

,index,Code,Description,Type,Package/Line_Level,Gross charge,Discounted cash price,De-identified min contracted rate,De-identified max contracted rate,Derived contracted rate,...,Optum-Commercial other,Oxford-Commercial other,Oxford-Commercial HMO/POS,Tricare-Commercial other,United Healthcare-Commercial other,United Healthcare-Medicare Advantage HMO,United Healthcare-Commercial HMO/POS,United Healthcare-Medicaid HMO,United Healthcare-Commercial PPO/Open Access,Veteran Family-Commercial other
0,0,10004,"FINE NEEDLE ASPIRATION BIOPSY, EACH ADDITIONAL...",Outpatient,Line,718.67,718.67,2155.50,2155.50,2155.50,...,None,NaN,None,None,NaN,None,None,NaN,None,None
1,1,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,2061.25,2061.25,87.02,4782.00,2308.44,...,None,4782.0,None,None,3845.25,None,None,658.94,None,None
2,2,10005,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Package,2061.25,2061.25,87.02,4782.00,2308.44,...,None,4782.0,None,None,3845.25,None,None,658.94,None,None
3,3,10006,FINE NEEDLE ASPIRATION BIOPSY USING ULTRASOUND...,Outpatient,Line,728.54,728.54,58.55,1761.25,909.90,...,None,NaN,None,None,NaN,None,None,NaN,None,None
4,4,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,2823.01,2823.01,446.28,6017.59,4219.31,...,None,NaN,None,None,5127.00,None,None,NaN,None,None
5,5,10009,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Package,2823.01,2823.01,446.28,6017.59,4219.31,...,None,NaN,None,None,5127.00,None,None,NaN,None,None
6,6,10010,FINE NEEDLE ASPIRATION BIOPSY OF GROWTH USING ...,Outpatient,Line,588.00,588.00,2155.50,2155.50,2155.50,...,None,NaN,None,None,NaN,None,None,NaN,None,None
7,7,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Line,1566.78,1566.78,275.46,2265.50,1270.48,...,None,NaN,None,None,NaN,None,None,NaN,None,None
8,8,10021,"FINE NEEDLE ASPIRATION BIOPSY, FIRST GROWTH",Outpatient,Package,1566.78,1566.78,275.46,2265.50,1270.48,...,None,NaN,None,None,NaN,None,None,NaN,None,None
9,9,10030,DRAINAGE OF FLUID COLLECTION IN SOFT TISSUE US...,Outpatient,Line,2082.05,2082.05,152.66,4101.00,1663.85,...,None,NaN,None,None,NaN,None,None,NaN,None,None